### ISSUE TITLE
Stack all-in-one

### ISSUE THREAD

**Issue by colinlaney** [ledovsky/alice-annotation-tool#2]
Gather all services within single docker-compose stack.

1. Add PosgreSQL service next to the others, e.g. `services: postgres:`
2. Substitute `host` network by docker's one, e.g. `network: annotation-network`
3. Parameterize mount points from host machine by environment variables, e.g. `volumes: $MEDIA_DATA:/django_media`

**Comment by ledovsky** [comment]
Does it seems like what you mean?

```
version: "3"

services:
  back:
    build: ./back
    ports:
      - 8000:8000
    env_file: ./back/.env
    volumes:
      - $MEDIA_DATA:/django_media
      - $STATIC_DATA:/django_static
      - ./out:/django_out
    depends_on:
      - postgres
  nginx:
    build: .
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - $MEDIA_DATA:/django_media:ro
      - $STATIC_DATA:/django_static:ro
    depends_on:
      - back
  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    env_file: ./postgres/.env
    volumes:
      - $POSTGRES_DATA:/var/lib/postgresql/data
```

**Comment by colinlaney** [comment]
Yes, but network setting should be more precise and explicit. For example,
```
services:
  service_name:
    networks:
      - reverse-proxy
 networks:
  reverse-proxy:
    external: true
```
